/** Hotels that get a personal proposal at /proposal/:slug. Slug = the hotel's *.hotelup.work subdomain. */
export interface ProposalHotel {
	slug: string;
	name: string;
	city: string;
}

export const PROPOSAL_HOTELS: ProposalHotel[] = [
	{ slug: 'arbat', name: 'Arbat', city: 'Чернівці' },
	{ slug: 'citycenter', name: 'City Center Residence', city: 'Чернівці' },
	{ slug: 'cityclub', name: 'City Club European', city: 'Чернівці' },
	{ slug: 'coin', name: 'Coin Apartments & Poshtel', city: 'Чернівці' },
	{ slug: 'leoton', name: 'Leoton Hotel', city: 'Чернівці' },
	{ slug: 'mirage', name: 'Mirage', city: 'Чернівці' },
	{ slug: 'oazis', name: 'Готель Оазис', city: 'Чернівці' },
	{ slug: 'panskyidvir', name: 'Панський Двір 2', city: 'Чернівці' },
	{ slug: 'pelican', name: 'Pelican Guest House & Hostel', city: 'Чернівці' },
	{ slug: 'tsapart', name: 'T&S apart-hotel', city: 'Чернівці' },
	{ slug: '7dniv', name: 'Готель «7 Днів»', city: 'Кам’янець-Подільський' },
	{ slug: 'anna', name: 'Готельно-ресторанний комплекс «Пані Анна»', city: 'Смотрич' },
	{ slug: 'apart247', name: 'Апарт-готель 24/7', city: 'Кам’янець-Подільський' },
	{ slug: 'apartratushi', name: 'Апартаменти у ратуші', city: 'Кам’янець-Подільський' },
	{ slug: 'astarta', name: 'Готель-ресторан «Астарта»', city: 'Кам’янець-Подільський' },
	{ slug: 'bakhus', name: 'Готель «Бахус»', city: 'Кам’янець-Подільський' },
	{ slug: 'bilyarichky', name: 'Готель «Біля річки»', city: 'Кам’янець-Подільський' },
	{ slug: 'bubbles', name: 'Bubbles', city: 'Кам’янець-Подільський' },
	{ slug: 'celebrity', name: 'Готельно-ресторанний комплекс «Знаменитій»', city: 'Кам’янець-Подільський' },
	{ slug: 'deluxe', name: 'Готельний комплекс «Делюкс»', city: 'Кам’янець-Подільський' },
	{ slug: 'dlyavsih', name: 'Для всіх', city: 'Кам’янець-Подільський' },
	{ slug: 'dynasty', name: 'Dynasty', city: 'Кам’янець-Подільський' },
	{ slug: 'elit-garden-hotel', name: 'Elit Garden Hotel', city: 'Кам’янець-Подільський' },
	{ slug: 'familylux', name: 'Міні-готель «Family Люкс»', city: 'Кам’янець-Подільський' },
	{ slug: 'filvarky', name: 'Фільварки Центр', city: 'Кам’янець-Подільський' },
	{ slug: 'florian', name: 'Florian', city: 'Кам’янець-Подільський' },
	{ slug: 'gala', name: 'Готельний комплекс «Гала Готель»', city: 'Кам’янець-Подільський' },
	{ slug: 'grandcanyon', name: 'Guesthouse GRAND CANYON', city: 'Кам’янець-Подільський' },
	{ slug: 'hetman', name: 'Готель «Гетьман»', city: 'Кам’янець-Подільський' },
	{ slug: 'inhotel', name: 'In Hotel', city: 'Кам’янець-Подільський' },
	{ slug: 'kapryz', name: 'Готель «Каприз»', city: 'Кам’янець-Подільський' },
	{ slug: 'kartafm', name: 'Гостинний дім «KARTA F.M.»', city: 'Кам’янець-Подільський' },
	{ slug: 'kleopatra', name: 'Готельно-ресторанний комплекс «Клеопатра»', city: 'Кам’янець-Подільський' },
	{ slug: 'konstantsiia', name: 'Міні-готель «Констанція»', city: 'Кам’янець-Подільський' },
	{ slug: 'ksenia', name: 'Готельно-ресторанний комплекс «Ксенія»', city: 'Кам’янець-Подільський' },
	{ slug: 'maria', name: 'Готель «Марія»', city: 'Кам’янець-Подільський' },
	{ slug: 'maxima', name: 'Maxima', city: 'Кам’янець-Подільський' },
	{ slug: 'minihome', name: 'Mini Home Hotel-Hostel', city: 'Кам’янець-Подільський' },
	{ slug: 'minihotel', name: 'Міні-готель', city: 'Кам’янець-Подільський' },
	{ slug: 'montecristo', name: 'Готель «Монте Крісто»', city: 'Кам’янець-Подільський' },
	{ slug: 'nazarstodolia', name: 'Назар Стодоля', city: 'Кам’янець-Подільський' },
	{ slug: 'optima', name: 'Optima Collection Kamianets-Podilsky', city: 'Кам’янець-Подільський' },
	{ slug: 'overture', name: 'Overture Studio', city: 'Кам’янець-Подільський' },
	{ slug: 'panorama', name: 'Panorama Apart-Hotel', city: 'Кам’янець-Подільський' },
	{ slug: 'pereveslo', name: 'База відпочинку «Перевесло»', city: 'Оринин' },
	{ slug: 'perlyna', name: 'Садиба «Смотрицька Перлина»', city: 'Кам’янець-Подільський' },
	{ slug: 'podillia', name: 'Оздоровчий комплекс «Поділля»', city: 'Кам’янець-Подільський' },
	{ slug: 'policmeister', name: 'Кав’ярня-музей «Кава від поліцмейстера»', city: 'Кам’янець-Подільський' },
	{ slug: 'ratusha', name: 'Ratusha craft rooms', city: 'Кам’янець-Подільський' },
	{ slug: 'redcube', name: 'Red Cube Hotel', city: 'Кам’янець-Подільський' },
	{ slug: 'romantic', name: 'Romantic Guest House', city: 'Кам’янець-Подільський' },
	{ slug: 'sadyba', name: 'Садиба', city: 'Смотрич' },
	{ slug: 'sercekanyona', name: 'Серце Каньйона', city: 'Кам’янець-Подільський' },
	{ slug: 'sherwood', name: 'Готельно-ресторанний комплекс «Шервуд Stream»', city: 'Слобідка-Кульчієвецька' },
	{ slug: 'solar', name: 'Готельно-розважальний комплекс «Solar»', city: 'Колибаївка' },
	{ slug: 'spadokhouse', name: 'Spadok House', city: 'Кам’янець-Подільський' },
	{ slug: 'stararus', name: 'Гостьовий будинок «Стара Русь»', city: 'Кам’янець-Подільський' },
	{ slug: 'sunrise', name: 'Гостьовий дім «SunRise»', city: 'Кам’янець-Подільський' },
	{ slug: 'svithub', name: 'Хостел «SvitHub»', city: 'Кам’янець-Подільський' },
	{ slug: 'tarasbulba', name: 'Тарас Бульба', city: 'Кам’янець-Подільський' },
	{ slug: 'teksas', name: 'Готель «Техас»', city: 'Кам’янець-Подільський' },
	{ slug: 'udominicana', name: 'Готель «У Домінікана»', city: 'Кам’янець-Подільський' },
	{ slug: 'yandrusi', name: 'Міні-готель «Яндрусі»', city: 'Кам’янець-Подільський' },
	{ slug: 'zigzag', name: 'Готельно-ресторанний комплекс «ЗІГ-ЗАГ»', city: 'Кам’янець-Подільський' },
];

export function findProposalHotel(slug: string | null | undefined): ProposalHotel | null {
	return PROPOSAL_HOTELS.find((hotel) => hotel.slug === slug) ?? null;
}
